
desc "Build for testing"
lane :custom_build_for_testing do |options|
  cocoapods(
    use_bundle_exec: true 
  )
  scan(
    derived_data_path: "DerivedData",
    clean: true
  )
end

desc "Run tests"
lane :custom_run_tests do |options|
  scan
end

desc "Build and test"
lane :custom_build_and_test do |options|
  custom_build_for_testing
  custom_run_tests
end