name: CI
on: [push]
jobs:
  build:
    runs-on: [self-hosted]
    steps:
    - uses: actions/checkout@v3
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1'
        bundler-cache: true
    - name: Build for testing
      run: |
        bundle exec fastlane custom_build_and_test
        
    - name: Update Link
      env:
        UPDATED_LINK: ${{ secrets.DISCORD }}
      run: |
        LINK=$UPDATED_LINK
        LINK=${LINK%/github}
        echo $LINK
        echo "UPDATED_LINK=$LINK" >> $GITHUB_ENV

    - name: Test Success
      uses: sarisia/actions-status-discord@v1
      if: success()
      with:
        webhook: ${{ env.UPDATED_LINK }}
        image: 'https://flexagon.com/wp-content/uploads/2020/04/a-world-with-ci.cd-meme.jpg'
        title: "deploy"
    - name: Test Failure
      uses: rjstone/discord-webhook-notify@v1
      if: failure()
      with:
        severity: error
        details: Test Failed!
        webhookUrl: ${{ secrets.DISCORD }}
    - name: Test Cancelled
      uses: rjstone/discord-webhook-notify@v1
      if: cancelled()
      with:
        severity: warn
        details: Test Cancelled!
        webhookUrl: ${{ secrets.DISCORD }}
