name: CI
on: [push]
jobs:
  build:
    runs-on: [self-hosted]
    steps:
    - uses: actions/checkout@v3
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1'
        bundler-cache: true
    - name: Build for testing
      run: |
        bundle exec fastlane custom_build_and_test
        
    - name: Update Link
      if: always()
      id: update_link
      run: |
        LINK=${{ secrets.DISCORD }}
        LINK=${LINK%/github}
        echo "::set-output name=updated_link::$LINK"

    - name: Test Success
      uses: sarisia/actions-status-discord@v1
      if: success()
      with:
        webhook: ${{ steps.update_link.outputs.updated_link }}
        username: 'Капитан Хук'
        image: 'https://flexagon.com/wp-content/uploads/2020/04/a-world-with-ci.cd-meme.jpg'
        avatar_url: 'https://www.chathamhouse.org/sites/default/files/styles/uncropped_tiny/public/2023-03/PinClipart.com_murder-clip-art_5376441.png?itok=zKK8nOOz'
        
    - name: Test Failure
      uses: sarisia/actions-status-discord@v1
      if: failure()
      with:
        webhook: ${{ steps.update_link.outputs.updated_link }}
        username: 'Капитан Хук'
        image: 'https://flexagon.com/wp-content/uploads/2020/04/a-world-without-ci.cd-meme.jpg'
        avatar_url: 'https://i.guim.co.uk/img/media/327e46c3ab049358fad80575146be9e0e65686e7/0_56_1023_614/master/1023.jpg?width=1200&height=900&quality=85&auto=format&fit=crop&s=1a1f3b8896b95c4590b3b7ae2d3b5d61'
        
    - name: Test Cancelled
      uses: sarisia/actions-status-discord@v1
      if: cancelled()
      with:
        webhook: ${{ steps.update_link.outputs.updated_link }}
        username: 'Капитан Хук'
        image: 'https://merriam-webster.com/assets/mw/images/article/art-wap-landing-mp-lg/cancel-button-on-computer-photo-6633-981fb4efe9bfd091834d0c167dd8c9a3@1x.jpg'
        avatar_url: 'https://chpic.su/_data/stickers/r/rzhumenpack/rzhumenpack_012.webp'
