name: CI
on: [push]
jobs:
  build:
    runs-on: [self-hosted]
    steps:
    - uses: actions/checkout@v3
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1'
        bundler-cache: true
    - name: Build for testing
      run: |
        bundle exec fastlane custom_build_and_test
    - uses: nebularg/actions-discord-webhook@v1
      if: always()
      with:
        webhook_url: ${{ secrets.DISCORD }}
        status: ${{ job.status }}
